### ISSUE TITLE
setting `type` breaks Edge/IE

### ISSUE THREAD

**Issue by gdibble** [AmpersandJS/ampersand-input-view#68] opened 2015-08-28 18:44 UTC
for example:

```
new InputView({
        name:        'assignmentDate',
        label:       'date',
        placeholder: 'mm/dd/yyyy',
        value:       this.model.assignmentDate,
        type:        'date',
        required:    true,
        parent:      this
      })
```

causes:

![image](https://cloud.githubusercontent.com/assets/906846/9554285/b523fff6-4d79-11e5-9b41-b14e2a9eb48d.png)

![image](https://cloud.githubusercontent.com/assets/906846/9554307/ca021cfa-4d79-11e5-8b6b-82449841e2f1.png)

**Comment by kylefarris** [comment] 2017-01-13 16:32
Yeah, I'm getting the same issue. No idea how to address this. I'd love to fix it and send a PR but I don't know what exactly the problem is. I'll do some investigating.

**Comment by dhritzkiv** [comment] 2017-01-13 16:48
I experienced this issue a _while_ back when working on IE 9, where I was passing in `"email"` as the `type`. It didn't like that (threw a non-helpful exception like the one in the issue). The solution was basically: `input.type = isIE9 ? "text": "email"`;

I see in your code snippet that you're trying to set the `type` to `"date"`, which appears to be unsupported in all versions of IE. I suspect that this lack of support is what is causing the exception. I don't know if there's a solution other than something like `input.type = isIE ? "text": "date"` and polyfilling a date picker UI. A date-specific UI isn't present in IE, anyway (nor is it in Safari, FWIW).

Can someone confirm that this is also happening in Edge (as the issue's title change suggests)? It shouldn't be, as Edge supports the date input field type (and is generally better behaved about things like this)

**Comment by dhritzkiv** [comment] 2017-07-04 14:31
Closing this as I believe the source is setting the `type` to `email`, or another value which IE9 doesn't support.

Feel free to reopen this if you believe this is incorrect and needs more investigation.

**Closed by dhritzkiv** 2017-07-04 14:31 UTC
Labels: help wanted, new contributor
